name: Deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Rollup'ı native paketi yerine JS sürümüne zorla (npm optional deps bug'ını by-pass)
      ROLLUP_USE_NODE_JS: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies (with fallback)
        run: |
          set -e
          # İlk deneme: deterministic kurulum
          npm ci || {
            echo "npm ci failed; applying workaround..."
            rm -rf node_modules package-lock.json
            npm install --no-audit --no-fund
          }

      # CRA ise (vite.config.* yok)
      - name: Build (CRA)
        if: ${{ hashFiles('vite.config.ts') == '' && hashFiles('vite.config.js') == '' }}
        run: npm run build

      # Vite ise (vite.config.* var)
      - name: Build (Vite)
        if: ${{ hashFiles('vite.config.ts') != '' || hashFiles('vite.config.js') != '' }}
        run: npm run build

      - name: Upload artifact (CRA build/)
        if: ${{ hashFiles('vite.config.ts') == '' && hashFiles('vite.config.js') == '' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Upload artifact (Vite dist/)
        if: ${{ hashFiles('vite.config.ts') != '' || hashFiles('vite.config.js') != '' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
