name: Deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]  # ana dalın 'main' değilse değiştir
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # CRA ise:
      - name: Build (CRA)
        if: ${{ !exists('vite.config.ts') && !exists('vite.config.js') }}
        run: npm run build

      # Vite ise BASE ayarıyla:
      - name: Set base for Vite (env)
        if: ${{ exists('vite.config.ts') || exists('vite.config.js') }}
        run: echo "VITE_BASE=/$GITHUB_REPOSITORY##*/"/ >> $GITHUB_ENV

      - name: Build (Vite)
        if: ${{ exists('vite.config.ts') || exists('vite.config.js') }}
        run: |
          # vite.config.* dosyanda base'i env'den okuyacak şekilde ayarla (aşağıdaki notlara bak)
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build  # Vite kullanıyorsan ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
